language: node_js
node_js:
  - '0.10'

addons:
  sauce_connect:
    username:
      secure: "UfeiLOFTWPtySuwtRj44gVId5OaeDexfHSLNtYWlYzDgzYzQZOl6tHkCWADIrQYgCdjoS3Zc7yDTpI3bTPV7Zs1jdbvc2WZNs87SMVyXmioQOYtHnDup02GEGJi9Bk0+GOBDsz7dXgmHXEiamFQD6cqYWfnrcOaiZqkwF/QAt0Q="
    access_key:
      secure: "FhhmdaYwrOJ6fA4aQTVGDH2AlNIlbPDuElzqBEWINZlTNpM0aEWSVT6XBWq+R51UOJrlrQSDco55dyldvHXu7oNhye0l0tZrFi9WcZxjVI4W8aKsYlHYoSbUxeKTySWz1KL5nhFQWoSOgIvVdv+c3Sa2S2XUsclvG9hnkHwH1D4="

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - npm run test-pre
  - if [[ $SAUCE_ACCESS_KEY == '' ]]; then npm test; fi
  - if [[ $SAUCE_ACCESS_KEY != '' ]]; then ./node_modules/karma/bin/karma start --browsers SauceIE6,SauceIE7,SauceIE8; fi
  - if [[ $SAUCE_ACCESS_KEY != '' ]]; then ./node_modules/karma/bin/karma start --browsers SauceIE9,SauceIE10,SauceIE11; fi
  - if [[ $SAUCE_ACCESS_KEY != '' ]]; then ./node_modules/karma/bin/karma start --browsers SauceFirefox,SauceSafari5; fi
  - if [[ $SAUCE_ACCESS_KEY != '' ]]; then ./node_modules/karma/bin/karma start --browsers SauceiOS7,SauceiOS6,SauceiOS5; fi
  - if [[ $SAUCE_ACCESS_KEY != '' ]]; then ./node_modules/karma/bin/karma start --browsers SauceiOS4,SauceAndroid; fi
